first/mnist/urls.py
from django.urls import path
from . import views

app_name = 'mnist'

urlpatterns = [
    path('', views.UploadView.as_view(), name='index'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('paint/', views.PaintView.as_view(), name='paint'),
    path('pdf_to_text/', views.Pdf_to_text_View.as_view(), name='pdf_to_text'),
]

first/project5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mnist.urls')),
]

first/mnist/models.py
from django.db import models

# Create your models here.

first/mnist/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    file = forms.ImageField(label='画像ファイル')

class KakikomiForm(forms.Form):
        file = forms.CharField(
        label='調べたい分野',
        max_length=100,
        required=True,
        help_text='必須',
        )
        check = forms.BooleanField(
        label="pdf",
        required=False,
        )

first/mnist/views.py
import base64
from io import BytesIO
import re
from django.shortcuts import redirect, render
from django.views import generic
from .forms import ImageUploadForm, KakikomiForm
from .lib import predict
import numpy as np
from PIL import Image
from .scraping import Scraping
from .scraping_pdf import Scraping_pdf
from .pdf_to_text import Pdf_to_text


class UploadView(generic.FormView):
    template_name = 'mnist/upload.html'
    form_class = KakikomiForm


    def form_valid(self, form):
     # アップロードファイル本体を取得
        Word = form.cleaned_data['file']
        Num_site = 3
        kind = form.cleaned_data["check"]
        # 推論した結果を、テンプレートへ渡して表示
        if kind:
            context = {
                'result': Scraping_pdf(Word,Num_site),
            }
        else:
            context = {
                'result': Scraping(Word,Num_site),
            }
        
        return render(self.request, 'mnist/result.html', context)
    

class Pdf_to_text_View(generic.FormView):
    template_name = 'mnist/pdf_to_text.html'
    form_class = KakikomiForm


    def form_valid(self, form):
     # アップロードファイル本体を取得
        pdf_url = form.cleaned_data['file']
        

        # 推論した結果を、テンプレートへ渡して表示
        context = {
            'result': Pdf_to_text(pdf_url),
        }
        return render(self.request, 'mnist/result.html', context)


class PaintView(generic.TemplateView):
    template_name = 'mnist/paint.html'

    def post(self, request):
        base_64_string = request.POST['img-src'].replace(
            'data:image/png;base64,', '')
        file = BytesIO(base64.b64decode(base_64_string))

        # ファイルを、28*28にリサイズし、グレースケール(モノクロ画像)
        img = Image.open(file).resize((28, 28)).convert('L')

        # 学習時と同じ形に画像データを変換する
        img_array = np.asarray(img) / 255
        img_array = img_array.reshape(1, 784)

        # 推論した結果を、テンプレートへ渡して表示
        context = {
            'result': predict(img_array),
        }
        return render(self.request, 'mnist/result.html', context)

first/mnist/templates/mnist/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/stylesheet.css">
       <!-- Favicons -->

<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
 

    
   <title>関連度高い順アプリ</title>
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <ul class="nav">
          <li class = "nav-item">
            <a class = "nav-link" href = "{% url 'mnist:index' %}">ホーム</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mnist:upload' %}">課題用</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mnist:pdf_to_text' %}">PDFのテキスト抽出</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mnist:paint' %}">お絵かき</a>
            </li>
          </ul>
        <div>
          <h3 class="float-md-start mb-0" style = "color: aqua;">試用版</h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">

            <a class="nav-link" href="#">お問い合わせ</a>
          </nav>
        </div>
      </header>
      


    
      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
</body>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</html>

first/mnist/templates/mnist/index.html
{% extends 'mnist/base.html' %}
{% block content %}
                                                      
{% endblock %}

first/mnist/templates/mnist/index1.html
<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="description" content="最新技術と自然との調和を目指す">
<meta name="viewport" content="width=device-width">
<title>SAMPLE COMPANY | 最新技術と自然との調和を目指す</title>
<link rel="stylesheet" media="all" href="../css/style.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="../js/script.js"></script>
</head>

<body id="top">
<header id="header">
	<div id="headerWrap">
		<h1><img src="../images/logo.png" width="142" height="80" alt="logo"></h1>
		<nav id="mainnav">
			<p id="menuWrap"><a id="menu"><span id="menuBtn"></span></a></p>
			<div class="panel">
				<ul>
					<li><a href="#top">TOP</a></li>
					<li><a href="#sec01">MESSAGE</a></li>
					<li><a href="#sec02">GALLERY</a></li>
					<li><a href="#sec03">PROJECT</a></li>
					<li><a href="#sec04">BRAND</a></li>
					<li><a href="#sec05">COMPANY</a></li>
				</ul>
			</div>
		</nav>
	</div>
</header>

<div id="mainImg">
	<img src="../images/mainImg.jpg" alt="">
</div>

<!-- MESSAGE -->
<section id="sec01">
	<header>
		<h2><span>Message</span></h2>
	</header>
	<div class="innerS">
		ちかごろ世間で日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいうには及ばないはずである。上にいったようなことがらについては、曖昧あいまいな態度をとり、または真実でない知識を強いて注入していたことも、明かな事実である。
	</div>
</section>
<!-- // MESSAGE -->

<!-- GALLERY -->
<section id="sec02">
	<header>
		<h2><span>Gallery</span></h2>
	</header>
	<ul id="gallery">
		<li><img src="../images/photo01.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo02.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo03.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo04.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo05.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo06.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo07.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo08.jpg" width="426" height="418" alt=""></li>
		<li><img src="../images/photo09.jpg" width="426" height="418" alt=""></li>
	</ul>
</section>
<!-- // GALLERY -->

<!-- PROJECT -->
<section id="sec03">
	<header>
		<h2><span>Project</span></h2>
	</header>
	<div class="innerS">
		<img src="images/imgProject.jpg" width="726" height="333" alt="">
		<p>ちかごろ世間で日本歴史の今さらこと新しくいうには科学的研究ということがしきりに叫ばれているということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいうには及ばないはずである。科学的研究というのが近代史学の学問的方法によるちかごろ世間で日本歴史の科学的研究及ばないはずである。</p>
	</div>
</section>
<!-- // PROJECT -->

<img src="images/subImg.jpg" alt="">

<!-- BRAND --> 
<section id="sec04">
	<header>
		<h2><span>Brand</span></h2>
	</header>
	<div class="inner">
		<ul class="col3">
			<li>
				<p class="img"><img src="images/logo01.png" width="170" height="106" alt=""></p>
				<p>科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
			</li>
			<li>
				<p class="img"><img src="images/logo02.png" width="170" height="106" alt=""></p>
				<p>日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば意義であるならば。</p>
			</li>
			<li>
				<p class="img"><img src="images/logo03.png" width="170" height="106" alt=""></p>
				<p>科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
			</li>
		</ul>
	</div>
	<div id="sec04_02">
		<p><img src="images/logoBrand.png" width="340" height="107" alt=""></p>
	</div>
</section>
<!-- // STORY -->

<!-- COMPANY -->
<section id="sec05">
	<header>
		<h2><span>Company</span></h2>
	</header>
	<div class="innerS">
		<ul class="col2">
			<li>
				<p>〒103-1234<br>見本県見本市仮区見本町1-3-5</p>
				<p>TEL 01234-567-8901</p>
				<p>e-Mail info@example.com</p>
				<p>営業時間 10:00〜20:00（水曜定休）</p>
				<p>※都合により休業する場合がございます</p>
				<p id="sns">
					<a href="#" target="_blank"><img src="images/iconFb.png" width="20" height="20" alt="FB"></a>
					<a href="#" target="_blank"><img src="images/iconTw.png" width="20" height="20" alt="twitter"></a>
					<a href="#" target="_blank"><img src="images/iconInsta.png" width="20" height="20" alt="Instagram"></a>
					<a href="#" target="_blank"><img src="images/iconYouTube.png" width="20" height="20" alt="You Tube"></a>
				</p>
			</li>
			<li>
				<div id="map">
					<!-- GOOGLE MAP -->
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3198.5937927089367!2d136.92980931491988!3d36.70829797996758!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5ff781ec5af4ca3f%3A0x2ade3e8e4c2801b8!2z56aP5bKh6aeF!5e0!3m2!1sja!2sus!4v1478313402186" allowfullscreen></iframe>
					<!-- // GOOGLE MAP -->
				</div>
			</li>
		</ul>
	</div>
</section>
<!-- // COMPANY -->

<footer id="footer">
	Copyright(c) 2016 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank">http://f-tpl.com</a><!-- ←クレジット表記を外す場合はシリアルキーが必要です http://f-tpl.com/credit/ -->
</footer>

</body>
</html>

first/mnist/templates/mnist/paint.html
{% extends 'mnist/base.html' %}

{% block content %}
<div class="container-xl">
<form action="" method="POST" enctype='multipart/form-data'>
<canvas id="canvas" width="140" height="140"></canvas>
<hr>
<input type="hidden" name="img-src" value="" id="img-src">
<input type="button" class="btn btn-outline-primary btn-lg" id="send" value="送信する">
{% csrf_token %}
</form>
{% endblock %}

{% block extrajs %}
<script>
// キャンバスを操作するためのオブジェクトを取得
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");

// キャンバスを黒く塗りつぶす
ctx.fillStyle = '#000';
ctx.fillRect(0, 0, 140, 140);

ctx.lineCap = 'square';  // 四角い形の線
ctx.strokeStyle = '#fff';  // 白い線
ctx.lineWidth = 13;  // 線の幅
var draw = false;  // クリック中かのフラグ

// マウスが動いたときに呼び出される
canvas.addEventListener("mousemove",function(e) {
  var rect = e.target.getBoundingClientRect();
  mouseX = e.clientX - rect.left;
  mouseY = e.clientY - rect.top;

  if(draw) {
    ctx.beginPath();
    ctx.moveTo(mouseX1,mouseY1);
    ctx.lineTo(mouseX,mouseY);
    ctx.stroke();
    mouseX1 = mouseX;
    mouseY1 = mouseY;
  }
});

// クリックで呼び出される
canvas.addEventListener("mousedown",function(e) {
  draw = true;
  mouseX1 = mouseX;
  mouseY1 = mouseY;
});

// クリックを離されると呼び出される
canvas.addEventListener("mouseup", function(e){
  draw = false;
});


// 送信ボタンで呼び出される
$('#send').on('click',function(e){
    var form = $(this).parents('form');
    var src = canvas.toDataURL('image/png');
    $('#img-src').val(src);
    form.submit();
});
</script>
</div>
{% endblock %}

first/mnist/templates/mnist/pdf_to_text.html
{% extends 'mnist/base.html' %}
{% block content %}

<h1>PDFのテキスト抽出を行います</h3>
  <p class="lead">文字起こししたいPDFファイルの<strong style = "color:rgb(0, 247, 164)">URL</strong>入力してください</p>
  <p style="color:rgb(255, 106, 106)">※pdfファイルをアップロードできるように改修中</p>
<div class="container-xl">
<form action="" method="POST" enctype='multipart/form-data'>
  {{ form.file }}<hr>
  {% csrf_token %}
  <button type="button" class="btn btn-secondary" onclick="location.reload()">URLを削除</button>
  <input type="submit" class="btn btn-outline-primary btn-lg" value="送信する">
</form>           
</div>                                                                                                       
{% endblock %}

first/mnist/templates/mnist/result.html
{% extends 'mnist/base.html' %}
{% block content %}
<div class="container-xl">

<button type="button" class="btn btn-primary" onclick="history.back()">違う単語で検索する</button>
<br><br>
<h1>結果は以下のようになりました</h1>

<p>{{ result|linebreaksbr }} </p>
</div>
{% endblock %}

first/mnist/templates/mnist/upload.html
{% extends 'mnist/base.html' %}
{% block content %}
<h1>関連用語を抽出します</h3>
    <p class="lead">調べたい単語を入れましょう．それに関連した単語を表示します</p>
    <div class="container-xl">
        <form action="" method="POST" enctype='multipart/form-data'>
            {{ form.file }}
            <hr>
            {% csrf_token %}
            {{ form.check }}pdf
            <br>
            <button type="button" class="btn btn-secondary" onclick="location.reload()">単語を削除</button>
            <input type="submit" class="btn btn-outline-primary btn-lg" value="送信する" id="checkButton">

        </form>
    </div>
    {% endblock %}